[build]
  publish = "." # Your index.html is in the root directory
  functions = "netlify/functions" # This tells Netlify where to find your functions

[[redirects]]
  from = "/log-search"
  to = "/.netlify/functions/log-search"
  status = 200
  # This redirect makes your client-side fetch('/log-search') work
  # by internally rewriting it to the function's actual path.
  # Otherwise, your client-side fetch would need to be '/.netlify/functions/log-search'
